cmake_minimum_required(VERSION 3.8)
project(drobot_msgs)

if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()

find_package(ament_cmake REQUIRED)
find_package(rosidl_default_generators REQUIRED)
find_package(std_msgs REQUIRED)
find_package(geometry_msgs REQUIRED)

# .msg 파일 → Python/C++ 코드 자동 생성
# 여기에 나열된 .msg 파일들이 빌드 시 import 가능한 형태로 변환됨
rosidl_generate_interfaces(${PROJECT_NAME}
  "msg/ModeSwitchPoint.msg"
  "msg/ModeSwitchPlan.msg"
  DEPENDENCIES std_msgs geometry_msgs
)

if(BUILD_TESTING)
  find_package(ament_lint_auto REQUIRED)
  ament_lint_auto_find_test_dependencies()
endif()

ament_package()
